css: ./node_modules/.bin/nodemon --ext css --exec "npm run build:css" --watch app/css
html: ./node_modules/.bin/nodemon --ext hbs --exec "npm run build:html" --watch app/pages --watch app/views
server: ./node_modules/.bin/browser-sync start --config config/browsersync.js
